VetOffice.WebMVC/Controllers/PetController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VetOffice.Data;
using VetOffice.Models;
using VetOffice.Services;

namespace VetOffice.WebMVC.Controllers
{
    public class PetController : Controller
    {
        // GET: Pet
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PetService(userId);
            var model = service.GetPets();
            return View(model);
        }

        private ApplicationDbContext db = new ApplicationDbContext();

        //GET
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PetCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreatePetService();
            if (service.CreatePet(model))
            {
                ViewBag.SaveResult = "Your pet was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Pet could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreatePetService();
            var model = svc.GetCustomerPetsById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var svc = CreatePetService();
            var detail = svc.GetPetById(id);
            var model = new PetEdit
            {
                PetId = detail.PetId,
                PetName = detail.PetName,
                TypeOfPet = detail.TypeOfPet,
                Breed = detail.Breed,
                AgeOfPet = detail.AgeOfPet
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PetEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.PetId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }
            var service = CreatePetService();
            if (service.UpdatePet(model))
            {
                TempData["SaveResult"] = "Your pet was updated.";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your pet could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePetService();
            var detail = svc.GetPetById(id);
            return View(detail);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreatePetService();
            service.DeletePet(id);
            TempData["SaveResult"] = "Your pet was deleted.";
            return RedirectToAction("Index");
        }

        public ActionResult CreateMultiple()
        {
            return View();
        }

        private PetService CreatePetService()
        {
            return new PetService(Guid.Parse(User.Identity.GetUserId()));
        }
    }
}

VetOffice.WebMVC/Views/Pet/Create.cshtml
@model VetOffice.Models.PetCreate

@{
    ViewBag.Title = "Create";
}

<div class="backgroundImageForDeleteForms">
    <div class="formContainer" style="height:550px;">
        <div class="container" style="padding-left:0; height:15%;">
            <p class="tableHeader" style="display: flex; justify-content:flex-start;">New Pet</p>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal" style="padding:0;">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group" style="font-size:1.2em;">
                    <p>Customer's Name</p>
                    <div class="col-md-10">
                        @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="font-size:1.2em;">
                    <p>Pet's Name</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="font-size:1.2em;">
                    <p>Type of Pet</p>
                    <div class="col-md-10">
                       @Html.EnumDropDownListFor(model => model.TypeOfPet, "Please select type of pet.", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group" style="font-size:1.2em;">
                    <p>Breed</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="font-size:1.2em;">
                    <p>Age of Pet</p>
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.AgeOfPet, "Please select age of pet.", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-control-lg">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add" class="btn btn-info btn-lg" />
                        <a class="btn btn-info btn-lg" href="@Url.Action("Index","Pet")">Back To List</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

VetOffice.WebMVC/Views/Pet/Delete.cshtml
@model VetOffice.Models.PetDetail

@{
    ViewBag.Title = "Delete";
}

<div class="backgroundImageForDeleteForms">
    <div class="formContainer" style="height:500px;">
        <div class="container" style="padding-left:0; height:20%;">
            <p class="tableHeader" style="display: flex; justify-content:flex-start;">Delete Pet</p>
        </div>

        <dl class="form-horizontal" id="lessPadding">

            <dt>
                @Html.DisplayNameFor(model => model.Customer.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PetName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PetName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TypeOfPet)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TypeOfPet)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Breed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Breed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AgeOfPet)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AgeOfPet)
            </dd>
        </dl>
        <br />
        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-control-lg">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-info btn-lg" />
                    <a class="btn btn-info btn-lg" href="@Url.Action("Index","Pet")">Back To List</a>
                </div>
            </div>
        }
    </div>
</div>

VetOffice.WebMVC/Views/Pet/Details.cshtml
@model VetOffice.Models.PetDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PetDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pets)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Pet Name</th>
                    <th>Pet Type</th>
                    <th>Pet Age</th>
                </tr>
                @foreach (var item in Model.Pets)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PetName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeOfPet)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AgeOfPet)
                    </td>
                </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PetId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VetOffice.WebMVC/Views/Pet/Edit.cshtml
@model VetOffice.Models.PetEdit

@{
    ViewBag.Title = "Edit";
}

<div class="backgroundImageForEditForms">
    <div class="formContainer" style="height:475px; padding-left:6%;">
        <div class="container" style="padding-left:0; height:17%;">
            <p class="tableHeader" style="display: flex; justify-content:flex-start;">Edit Pet</p>
            <br />
            <br />
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal" id="edit" style="padding-left:5%; font-size: 1.3em;">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PetId)

                <div class="form-group">
                    <p>Pet Name</p>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.PetName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PetName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Type of Pet</p>
                    <div class="col-md-10" style="color:#808080">
                        @Html.EnumDropDownListFor(model => model.TypeOfPet, "Please select type of pet.", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    <p>Breed</p>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Age of Pet</p>
                    <div class="col-md-10" style="color:#808080">
                        @Html.EnumDropDownListFor(model => model.AgeOfPet, "Please select age of pet.", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group-lg" style="padding-top: 3%;">
                    <div class="col-md-offset-2 col-md-3" style="padding-top: 2%; padding-left: 7%; margin: 0;">
                        <input type="submit" style="padding-left:26%; padding-right:26%;" value="Save" class="btn btn-info btn-lg">
                    </div>
                    <div class="col-md-offset-2 col-md-6" style="padding-top: 2%; padding-left: 10%; margin: 0;">
                        <a class="btn btn-info btn-lg" style="padding-left:10%; padding-right:10%;" href="/Pet">Back To List</a>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

VetOffice.WebMVC/Views/Pet/Index.cshtml
@model IEnumerable<VetOffice.Models.InfoListItem>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h1 class="tableHeader">Our Customers & Pets</h1>
    <br />
    <a class="btn btn-info btn-lg" href="@Url.Action("Create","Pet")">Add Pet</a>
    <br />
    <br />
    <br />
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th scope="col">
                Pet Name
            </th>
            <th scope="col">
                Pet Type
            </th>
            <th scope="col">
                Pet Breed
            </th>
            <th scope="col">
                Pet Age
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="table table-secondary">
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @foreach (var pet in item.Pets)
                    {
                        <div> @Html.DisplayFor(modelItem => pet.PetName)</div>
                        <br />
                    }
                </td>
                <td>
                    @foreach (var pet in item.Pets)
                    {
                        <div> @Html.DisplayFor(modelItem => pet.TypeOfPet)</div>
                        <br />
                    }
                </td>
                <td>
                    @foreach (var pet in item.Pets)
                    {
                        <div> @Html.DisplayFor(modelItem => pet.Breed)</div>
                        <br />
                    }
                </td>
                <td>
                    @foreach (var pet in item.Pets)
                    {
                        <div> @Html.DisplayFor(modelItem => pet.AgeOfPet)</div>
                        <br />
                    }
                </td>
                <td>
                    @foreach (var pet in item.Pets)
                    {
                        <button class="btn btn-info btn-lg"> @Html.ActionLink("Edit", "Edit", "Pet", new { id = pet.PetId }, null)</button>
                        <button class="btn btn-info btn-lg"> @Html.ActionLink("Delete", "Delete", "Pet", new { id = pet.PetId }, null)</button>
                        <br /><br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<br />
<div class="clients">
    <p>We <span class="glyphicon"> &hearts;</span> our Cute Clients ...</p>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="card mb-3" style="width: 280px;">
            <h3 class="card-header">Tiger</h3>
            <img style="height: 200px; width: 100%; display: block;" src="~/Content/assets/Clients/kitten-peaking-through-greenery_4460x4460.jpg" alt="Card image">
            <div class="card-body">
                <p class="card-text">Tiger, you are definitely a little tiger! Ready to pounce, the world (and your siblings) better watch out!</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card mb-3" style="width: 280px;">
            <h3 class="card-header">Milo</h3>
            <img style="height: 200px; width: 100%; display: block;" src="~/Content/assets/Clients/dog-1191676_1920.jpg" alt="Card image">
            <div class="card-body">
                <p class="card-text">Oh Milo, what can we say?! We hope you don't have to spend too much time in the cone of shame!</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card mb-3" style="width: 280px;">
            <h3 class="card-header">Naomi</h3>
            <img style="height: 200px; width: 100%; display: block;" src="~/Content/assets/Clients/kate-stone-matheson-1141289-unsplash.jpg" alt="Card image">
            <div class="card-body">
                <p class="card-text">What a sweet cuddler Naomi is! With such a sweet disposition, we love when Naomi pays us a visit!</p>
            </div>
        </div>
    </div>
</div>